import TopBar from "@/components/TopBar/TopBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/provider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Charity Wave",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TopBar />
          <Navbar />
          <div className="min-h-[calc(100vh-430px)]">
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
